### PR TITLE
Tried adding a tv control option. But..

### PR DESCRIPTION
**Pull request by shash235**
The program does not start up for me for some reason. Not sure if its a problem with my browser. I tried changing the values for the size and the x, y values as well but still no luck.

### CODE REVIEW

**Comment by mrshinx** [comment]
Will take a look at it later. In the mean time, you can track bugs on Chrome browser by right clicking the page, choose inpsect, then switch to console tab to see what is causing the problem

**Comment by mrshinx** [comment]
Just realized at line 399 you used buttons, but that name has already been used by me in my case lol

**Comment by shash235** [comment]
oh yeah I should've changed the name

**Comment by shash235** [comment]
Yeah that was the error thanks. Just have to realign the images again

**Pull request closed without merging**
